name: sdk_pss_app
description: Parking App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  shared_preferences: ^2.0.12
  provider: ^6.0.2
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  flutter_blue: ^0.8.0
  beacon_broadcast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  mocktail: ^0.2.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^1.1.0

flutter:
  uses-material-design: true
